# Generated by Django 5.1 on 2024-08-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='name',
            new_name='title',
        ),
    ]
