# Generated by Django 5.1 on 2024-08-26 14:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_name_show_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='videos',
        ),
        migrations.AddField(
            model_name='show',
            name='frame_count',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MaxValueValidator(9000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='preview_frame',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.show'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
