# Generated by Django 5.1 on 2024-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_show_videos_show_frame_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('in_design', 'In Design'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('showing', 'Showing'), ('archived', 'Archived')], default='in_design', max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='preview_frame',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
