# Generated by Django 5.1 on 2024-08-29 10:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_show_status_alter_show_preview_frame'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('show', 'file')},
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(226)])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='videos.show')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='videos.video')),
            ],
            options={
                'unique_together': {('show', 'location_number')},
            },
        ),
    ]
